apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource 
metadata:
  name: room-service-mongo      # Name of the service
  labels:                         # Labels that will be applied to the service
    app: room-service
spec:
  ports:
    - port: 27017
  selector:                       # Selects any Pod with labels `app=review-service,tier=mongo`
    app: room-service
    tier: mongo
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment                    # Type of the kubernetes resource
metadata:
  name: room-service-mongo-deployment           # Name of the deployment
  labels:                           # Labels applied to this deployment 
    app: room-service
spec:
  selector:
    matchLabels:                    # This deployment applies to the Pods matching the specified labels
      app: room-service
      tier: mongo
  strategy:
    type: Recreate
  template:                         # Template for the Pods in this deployment
    metadata:
      labels:                       # Labels to be applied to the Pods in this deployment
        app: room-service
        tier: mongo
    spec:                           # The spec for the containers that will be run inside the Pods in this deployment
      containers:
      - image: mongo                # The container image
        name: mongo
        ports:
        - containerPort: 27017        # The port that the container exposes       
          name: mongo
---
apiVersion: apps/v1           # API version
kind: Deployment              # Type of kubernetes resource
metadata:
  name: room-service-server-deployment    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: room-service-server
spec:
  replicas: 1                 # No. of replicas/pods to run in this deployment
  selector:
    matchLabels:              # The deployment applies to any pods mayching the specified labels
      app: room-service-server
  template:                   # Template for creating the pods in this deployment
    metadata:
      labels:                 # Labels that will be applied to each Pod in this deployment
        app: room-service-server
    spec:                     # Spec for the containers that will be run in the Pods
      containers:
      - name: room-service-server
        image: keuppenst/room-service
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8051 # The port that the container exposes
        resources:
          limits:
            cpu: 0.2
            memory: "200Mi"
        env:                    # Environment variables supplied to the Pod
        - name: MONGODB_HOST
          value: "room-service-mongo"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1                   # API version
kind: Service                    # Type of the kubernetes resource
metadata:                     
  name: room-service-server    # Name of the service
  labels:                        # Labels that will be applied to this service
    app: room-service-server
spec:                         
  type: NodePort                 # The service will be exposed by opening a Port on each node and proxying it. Allowing connections from outside the cluster
  selector:
    app: room-service-server   # The service exposes Pods with label `app=review-service-server`
  ports:                         # Forward incoming connections on port 8052 to the target port 8052
  - name: http
    port: 8051
    targetPort: 8051